s=set()
s.add(input("Enter your number: " ))
s.add(input("Enter your number: " ))
s.add(input("Enter your number: " ))
s.add(input("Enter your number: " ))
s.add(input("Enter your number: " ))
s.add(input("Enter your number: " ))
s.add(input("Enter your number: " ))
s.add(input("Enter your number: "))
print(s)